# Generated by Django 5.0.4 on 2024-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_examattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
    ]
